name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Installation de pnpm (obligatoire car non inclus par défaut sur Ubuntu)
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9 # Vous pouvez spécifier '8' si vous utilisez une ancienne version

      # 2. Configuration de Node.js avec le cache défini sur 'pnpm'
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # 3. Installation des dépendances (étape manquante dans votre code initial)
      - name: Install dependencies
        run: pnpm install

      # 4. Build du projet
      - name: Build project
        run: pnpm run build
        env:
          VITE_AUTH0_DOMAIN: ${{ secrets.VITE_AUTH0_DOMAIN }}
          VITE_AUTH0_CLIENT_ID: ${{ secrets.VITE_AUTH0_CLIENT_ID }}

      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4